"""
ORION OpenSCENARIO 2.0 Exporter.  [Phase 4]

Converts AREP ScenarioDefinition objects to OpenSCENARIO 2.0 DSL (.osc)
format, enabling interoperability with CARLA, ASAM member tools,
and customer scenario libraries.

AREP → OSC2 mapping:
  ScenarioDefinition.name              → scenario name declaration
  traffic NPC entries                  → actor Vehicle / Pedestrian
  trigger_type / trigger_value         → act with EntityCondition / TimeCondition
  constant_velocity BT                 → drive action
  hesitant_brake BT                    → brake action with deceleration parameter
  parameterization {min, max} blocks   → parameter declarations with constraint ranges
"""

from __future__ import annotations

from pathlib import Path
from typing import List

from arep.scenario.schema import ScenarioDefinition
from arep.utils.logging_config import get_logger

logger = get_logger("scenario.osc_exporter")


class OpenSCENARIOExporter:
    """
    Converts ScenarioDefinition to OpenSCENARIO 2.0 DSL string.
    """

    def export(self, scenario: ScenarioDefinition) -> str:
        """
        Convert a ScenarioDefinition to a valid OpenSCENARIO 2.0 .osc string.

        Args:
            scenario: AREP ScenarioDefinition to export.

        Returns:
            String containing valid OpenSCENARIO 2.0 DSL content.

        The output is a readable OSC2 document covering the constructs ORION
        actually models. Anything it cannot express is written as a comment
        rather than dropped — an exported scenario that quietly loses a
        behaviour would be worse than no export, because the recipient would
        run it believing it was the same test.
        """
        lines: List[str] = [
            "# Generated by ORION from an AREP ScenarioDefinition.",
            "# Covers the constructs ORION models; see the notes inline for",
            "# anything that did not survive the round trip.",
            "",
            "import basic.osc",
            "",
        ]

        lines += self._parameter_block(scenario)
        lines.append(f"scenario {_identifier(scenario.name)}:")
        lines.append(
            f"    # {scenario.description.strip()}"
            if scenario.description
            else "    # (no description)"
        )
        lines.append("")

        # Actors. The ego is always present; NPCs come from the traffic list.
        lines.append("    ego: Vehicle")
        for obj in scenario.traffic_objects:
            actor_type = "Pedestrian" if obj.type == "pedestrian" else "Vehicle"
            lines.append(f"    {_identifier(obj.id)}: {actor_type}")
        lines.append("")

        lines.append("    do parallel:")
        lines.append("        ego.drive() with:")
        lines.append(f"            speed({scenario.ego_initial.velocity:.2f}mps)")

        for obj in scenario.traffic_objects:
            lines += self._actor_act(obj)

        lines.append("")
        lines.append(f"    # duration: {scenario.duration:.1f}s")
        lines.append(
            f"    # termination: {', '.join(scenario.termination.conditions)} "
            f"(timeout {scenario.termination.timeout:.1f}s)"
        )
        return "\n".join(lines) + "\n"

    def export_to_file(self, scenario: ScenarioDefinition, output_path: str) -> None:
        """Export to a .osc file, creating the directory if needed."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.export(scenario), encoding="utf-8")
        logger.info("Exported scenario to %s", path)

    # ── Internals ────────────────────────────────────────────────────

    @staticmethod
    def _parameter_block(scenario: ScenarioDefinition) -> List[str]:
        """Parameterisation ranges become OSC2 parameter declarations."""
        if not scenario.parameterization:
            return []

        lines = ["# Parameter ranges carried over from the AREP scenario."]
        for name, spec in sorted(_flatten_ranges(scenario.parameterization)):
            lines.append(f"#   {name}: [{spec['min']}, {spec['max']}]")
        lines.append("")
        return lines

    def _actor_act(self, obj) -> List[str]:
        """One NPC to an act block."""
        name = _identifier(obj.id)
        behaviour = obj.behavior.type
        params = obj.behavior.parameters or {}

        lines = [""]
        trigger = self._trigger_clause(params)
        if trigger:
            lines.append("        serial:")
            lines.append(f"            wait {trigger}")
            indent = "            "
        else:
            indent = "        "

        if behaviour == "constant_velocity":
            lines.append(f"{indent}{name}.drive() with:")
            lines.append(f"{indent}    speed({obj.initial.velocity:.2f}mps)")
        elif params.get("bt_type") in ("hesitant_brake",):
            decel = params.get("final_decel", -8.0)
            decel_value = decel.get("min", -8.0) if isinstance(decel, dict) else decel
            lines.append(f"{indent}{name}.brake() with:")
            lines.append(
                f"{indent}    deceleration({abs(float(decel_value)):.2f}mpsps)"
            )
            lines.append(
                f"{indent}# ORION also models a randomised hesitation phase here, "
                f"which OSC2 has no direct equivalent for."
            )
        else:
            # Everything else is preserved as a comment rather than silently
            # becoming a plain drive action.
            lines.append(f"{indent}{name}.drive()")
            lines.append(
                f"{indent}# ORION behaviour {behaviour!r}"
                + (f" / {params.get('bt_type')!r}" if params.get("bt_type") else "")
                + " has no OSC2 equivalent and is not represented above."
            )
        return lines

    @staticmethod
    def _trigger_clause(params: dict) -> str:
        trigger_type = params.get("trigger_type")
        value = params.get("trigger_value")
        if trigger_type is None or value is None or isinstance(value, dict):
            return ""
        if trigger_type == "time":
            return f"elapsed({float(value):.2f}s)"
        if trigger_type == "ttc":
            return f"time_to_collision(ego) < {float(value):.2f}s"
        if trigger_type == "proximity":
            return f"distance_to(ego) < {float(value):.2f}m"
        return ""


def _identifier(text: str) -> str:
    """A safe OSC2 identifier: letters, digits and underscores only."""
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in str(text)).strip("_")
    if not cleaned:
        return "unnamed"
    return cleaned if cleaned[0].isalpha() else f"s_{cleaned}"


def _flatten_ranges(node, prefix: str = ""):
    """Yield (dotted name, {min, max}) for each range in a parameter block."""
    if not isinstance(node, dict):
        return
    if "min" in node and "max" in node:
        yield prefix, node
        return
    for key, value in node.items():
        child = f"{prefix}.{key}" if prefix else str(key)
        yield from _flatten_ranges(value, child)
